import type { Metadata } from "next";
import "./globals.css";
import Header from "./views/Header/page";

export const metadata: Metadata = {
  title: "演示交易",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-sans antialiased">
        <Header />
        {children}
      </body>
    </html>
  );
}
